
sudo: required

services:
  - docker

script:
  - docker build -t rakshans1/ionic-fastlane .
  - docker run rakshans1/ionic-fastlane /bin/sh -c "android list && node -v && npm -v && ionic -v && fastlane --version"